on:
  push:
      branches:
        - main
jobs:
  compile-subjects:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout glowing enigma
        uses: actions/checkout@v4
        with:
          repository: kafitimi/glowing-enigma

      - name: Checkout luminous riddle
        uses: actions/checkout@v4
        with:
          path: luminous-riddle

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install required packages
        run: |
          pip install -r requirements.txt
          pip install Levenshtein

      - name: Run build script
        run: python luminous-riddle/main.py

      - name: Publish matrices
        uses: actions/upload-artifact@v4
        with:
          name: Matrices
          path: ./luminous-riddle/plans/*.txt
