on:
  push:
      branches:
        - main
jobs:
  compile-subjects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: kafitimi/glowing-enigma

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: pip install -r glowing-enigma/requirements.txt
