on:
  push:
      branches:
        - main
jobs:
  compile-subjects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: kafitimi/glowing-enigma
