on:
  push:
      branches:
        - main
jobs:
  compile-subjects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout glowing enigma
        uses: actions/checkout@v4
        with:
          repository: kafitimi/glowing-enigma

      - name: Checkout glowing enigma
        uses: actions/checkout@v4
        with:
          path: luminous-riddle

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install required packages
        run: pip install -r requirements.txt

      - run: ls -la luminuos-riddle

      # - name: Run build script
      #   run: python main.py
